version: "3.9"

services:
  adoptask-api:
    build: ./adoptask-api
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - protectoras_files:/app/protectoras
      - usuarios_files:/app/usuarios
    environment:
      TZ: "Europe/Madrid"
      SPRING_DATA_MONGODB_URI: mongodb://root:root@mongo:27017/AdopTask?authSource=admin
    depends_on:
      - mongo

  adoptask-ui:
    build: ./adoptask-ui
    restart: always
    ports:
      - "80:80"
    depends_on:
      - adoptask-api

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    depends_on:
      - mongo

volumes:
  mongo_data:
  protectoras_files:
  usuarios_files:
