package adoptask.modelo;

public enum TipoPermiso {

	CREATE_ANIMALES, READ_ANIMALES, UPDATE_ANIMALES, DELETE_ANIMALES, CREATE_TAREAS, READ_TAREAS, UPDATE_TAREAS,
	DELETE_TAREAS, CREATE_DOCUMENTOS, READ_DOCUMENTOS, DELETE_DOCUMENTOS
}
